export const SUBCATEGORY_CREATE_REQUEST = 'SUBCATEGORY_CREATE_REQUEST'
export const SUBCATEGORY_CREATE_SUCCESS = 'SUBCATEGORY_CREATE_SUCCESS'
export const SUBCATEGORY_CREATE_FAIL = 'SUBCATEGORY_CREATE_FAIL'
export const SUBCATEGORY_CREATE_RESET = 'SUBCATEGORY_CREATE_RESET'
